# Generated by Django 2.2.7 on 2019-11-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=32, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=32, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('first_cell_index', models.CharField(blank=True, max_length=32, null=True)),
                ('second_cell_index', models.CharField(blank=True, max_length=32, null=True)),
                ('min_row', models.IntegerField(blank=True, null=True)),
                ('max_row', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
