# Generated by Django 2.2.7 on 2019-12-04 17:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20191204_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/kevit/source/trafficintel/testproject/testproject'), upload_to=''),
        ),
    ]
