# Generated by Django 2.2.7 on 2019-12-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20191204_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='first_cell_index',
        ),
        migrations.RemoveField(
            model_name='report',
            name='max_row',
        ),
        migrations.RemoveField(
            model_name='report',
            name='min_row',
        ),
        migrations.RemoveField(
            model_name='report',
            name='second_cell_index',
        ),
    ]
