# Generated by Django 2.2.7 on 2019-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20191205_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(blank=True, max_length=32, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
